[functions]

[functions.auth]
verify_jwt = false

[functions.galeria]
verify_jwt = true

[functions.musica]
verify_jwt = true

[functions.recuerdos]
verify_jwt = false

[functions.upload]
verify_jwt = false

[functions.search]
verify_jwt = false

[functions.stats]
verify_jwt = false

[functions.export]
verify_jwt = false

[functions.auditoria]
verify_jwt = true

[api]
enabled = true