name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel
        run: vercel deploy --prod --yes --token="${{ secrets.VERCEL_TOKEN }}" --scope="team_kiyDYH05TcOgl7saOwBi2N4H"
        env:
          VERCEL_ORG_ID: team_kiyDYH05TcOgl7saOwBi2N4H
          VERCEL_PROJECT_ID: prj_2RB5iSSwApAbiZBBtiT3pCIfd41A